### ISSUE TITLE
It still creates directories in "C:\Users\<User>\AppData\Roaming" and "C:\Users\<User>"

### ISSUE THREAD

**Issue by pbakes** [UnlimitedCookies/AtomEnterpriseInstaller#2]
I'm looking for a completely portable install of 1.55 for Windows 10.
Did this install as intended or did I not do something correctly?

**Comment by UnlimitedCookies** [comment]
It shouldn't put anything inside `C:\Users\<Users>\AppData\Roaming` except some automatically created cache files maybe.
`C:\Users\<User>` shouldn't be affected at all by the installation. This is because the script only unzips the Zip to `%programfiles%\Atom` and then manually creates desktop shortcuts. 

Can you please provide some more information on how you actually used the installer?

**Comment by UnlimitedCookies** [comment]
Closing as there has been no response.
